apiVersion: apps/v1
kind: Deployment
metadata:
  name: autonity-cli-deployment
spec:
  selector:
    matchLabels:
      app: autonity-cli
  replicas: 1
  template:
    metadata:
      labels:
        app: autonity-cli
    spec:
      containers:
      - name: autonity-cli
        image: your-repository/autonity-cli:latest
        volumeMounts:
        - name: keystore-volume
          mountPath: /k-keystore
      volumes:
      - name: keystore-volume
        persistentVolumeClaim:
          claimName: keystore-pvc
