apiVersion: v1
kind: Service
metadata:
  name: autonity-node-service
  namespace: "{{ .Values.namespace }}"
spec:
  type: NodePort
  selector:
    app: autonity-node
  ports:
  - name: http
    protocol: TCP
    port: 8545
    targetPort: 8545
    nodePort: {{ .Values.autonityNode.nodePorts.http }}
  - name: ws
    protocol: TCP
    port: 8546
    targetPort: 8546
    nodePort: {{ .Values.autonityNode.nodePorts.ws }}
  - name: p2p
    protocol: TCP
    port: 30303
    targetPort: 30303
    nodePort: {{ .Values.autonityNode.nodePorts.p2p }}
